storage: /verdaccio/storage
plugins: /verdaccio/plugins

web:
  title: Verdaccio Markplace Registry

auth:
  htpasswd:
    file: /verdaccio/conf/htpasswd
    max_users: 1000

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

middlewares:
  audit:
    enabled: true

log:
  - { type: stdout, format: pretty, level: http }

listen: 0.0.0.0:4873
url_prefix: /verdaccio/registry/
